x-common-service: &common-service
  env_file:
    - .env
  depends_on:
    - db
    - redis

x-web-common: &web-common
  <<: *common-service
  labels:
    - 'traefik.enable=true'
    - 'traefik.http.routers.web.rule=Host(`app.latitude.localhost`)'
    - 'traefik.http.services.web.loadbalancer.server.port=8080'
  depends_on:
    - db
    - redis
    - traefik

x-gateway-common: &gateway-common
  <<: *common-service
  labels:
    - 'traefik.enable=true'
    - 'traefik.http.routers.gateway.rule=Host(`gateway.latitude.localhost`)'
    - 'traefik.http.services.gateway.loadbalancer.server.port=8081'

x-websockets-common: &websockets-common
  <<: *common-service
  labels:
    - 'traefik.enable=true'
    - 'traefik.http.routers.websockets.rule=Host(`ws.latitude.localhost`)'
    - 'traefik.http.services.websockets.loadbalancer.server.port=4002'

services:
  mailpit:
    image: axllent/mailpit
    ports:
      - 8025:8025
      - 1025:1025
    profiles:
      - development

  traefik:
    image: traefik:v2.10
    command:
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--entrypoints.web.address=:80'
    ports:
      - '80:80'
      - '8090:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  db:
    image: postgres:15.8
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - ./docker/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - ./docker/pgdata:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - '6379:6379'

  web-local:
    <<: *web-common
    image: latitude/web:latest
    build:
      context: .
      dockerfile: apps/web/docker/Dockerfile

    profiles:
      - local

  web:
    <<: *web-common
    image: ghcr.io/latitude-dev/web:latest
    platform: linux/amd64

  migrations-local:
    <<: *common-service
    image: latitude/migrations:latest
    build:
      context: .
      dockerfile: packages/core/docker/Dockerfile

    depends_on:
      - db
    profiles:
      - local

  migrations:
    <<: *common-service
    image: ghcr.io/latitude-dev/migrations:latest
    platform: linux/amd64
    depends_on:
      - db

  gateway-local:
    <<: *gateway-common
    image: latitude/gateway:latest
    build:
      context: .
      dockerfile: apps/gateway/docker/Dockerfile

    profiles:
      - local

  gateway:
    <<: *gateway-common
    image: ghcr.io/latitude-dev/gateway:latest
    platform: linux/amd64

  workers-local:
    <<: *common-service
    image: latitude/workers:latest
    build:
      context: .
      dockerfile: apps/workers/docker/Dockerfile

    profiles:
      - local

  workers:
    <<: *common-service
    image: ghcr.io/latitude-dev/workers:latest
    platform: linux/amd64

  websockets-local:
    <<: *websockets-common
    image: latitude/websockets:latest
    build:
      context: .
      dockerfile: apps/websockets/docker/Dockerfile

    profiles:
      - local

  websockets:
    <<: *websockets-common
    image: ghcr.io/latitude-dev/websockets:latest
    platform: linux/amd64
